name: Push dist.sufu.site

on:
  push:
    branches: [ master ]

jobs:
  Main:
    runs-on: ubuntu-latest
    steps:
      - name: 获取主库源码
        uses: actions/checkout@v2

      - name: 获取 dist 仓库
        uses: actions/checkout@v2
        with:
          ref: master
          repository: sufuwang/dist.sufu.site
          token: ${{ secrets.DISTSUFUSITE }}
          path: ./dist.sufu.site

      - name: 执行脚本
        run: |
          ls
          rm -rf ./dist.sufu.site/book
          cp -r ./docs/.vitepress/dist/ ./dist.sufu.site/book
          ls
